Update the virtual env python version
Update the virtual env python version. Following the tutorial, the terminal outputs the following error
``` bash
RuntimeError: Python version >= 3.8 required.
```